### ISSUE TITLE
Init Cargo Project and Nix Flake

### ISSUE THREAD

**Issue by gabr1sr** [cyberzsk/czchat#2]
As this repo already have files in it, we must initiate a new cargo project in the project root.

Would be cool if we also add support to Flake (Nix).

## TODOs
- [x] `cargo init` in the project root
- [x] `nix flake init` in the project root
- [x] Add necessary packages to the `flake.nix`
- [x] Verify if system has the `nix flake` command and use it if existent, in the `.envrc`
